- lib/tentacat/repositories/deployments.ex
> Management of repo deployments

- lib/tentacat/repositories/merges.ex
As described in the [docs](https://developer.github.com/v3/repos/merging/#perform-a-merge).
> Add ability to merge repository branches

- mix.exs
Current version is 1.1.1. Are there any know compatibilities with this library?
> Relax Elixir dependency

- README.md
A small but often helpful addition, for the new and lazy like myself.
> adds mix dependency info to README

- .travis.yml
- README.md
- mix.exs
First of all thanks for creating this great project.
As I'm planing to use it in one of my upcoming side projects I will need to extend the current functionality.
While doing that I would like to increase the test coverage as this is something that makes me a bit worried.
This pull request would be the first step to increase the coverage. awareness :)
> Adds test coverage badge to the projects

- lib/tentacat/commits.ex
- lib/tentacat/releases.ex
- lib/tentacat/repositories/tags.ex
* allow latest release
* repos/commits apis
* tags list api
I haven't added tests (yet) let me know if I should record some responses or if this is enough.
thanks for the project!
> Add some apis

- lib/tentacat.ex
Conditionals are bad(tm).
Cfr. https://github.com/ShaneWilton/stockastic/pull/1
> Refactor `process_response` with multiple heads and pattern-matching

- lib/tentacat/repositories.ex
Modified Tentacat.Repositories.list_mine function to receive opts.
> Modified Tentacat.Repositories.list_mine function to receive opts.

- lib/tentacat/issues/labels.ex
- lib/tentacat/pulls.ex
- test/fixture/vcr_cassettes/issues/labels#add.json
- test/fixture/vcr_cassettes/issues/labels#list.json
- test/fixture/vcr_cassettes/pulls#has_been_merged.json
- test/fixture/vcr_cassettes/pulls#merge.json
- test/issues/labels_test.exs
- test/pulls_test.exs
- Pull request merge
- Pull request has_been_merged
- Issue Label list
- Issue Label add
- Add tests/fixtures for new features
These are features I will need for my own application, so I'm submitting them as a PR to the main Repo. Please let me know what you think!
> Adds 'Pulls.merge', 'Issue.Label.list', 'Issue.Label.add'

- lib/tentacat/issues/events.ex
- lib/tentacat/issues/issues.ex
- test/fixture/vcr_cassettes/issues/events#list.json
- test/issues/events_test.exs
> Update issues documentation

- README.md
- lib/tentacat/organizations/teams.ex
- test/fixture/vcr_cassettes/organizations/teams#create.json
- test/fixture/vcr_cassettes/organizations/teams#delete.json
- test/fixture/vcr_cassettes/organizations/teams#find.json
- test/fixture/vcr_cassettes/organizations/teams#list.json
- test/fixture/vcr_cassettes/organizations/teams#update.json
- test/organizations/teams_test.exs
As documented [here](https://developer.github.com/v3/orgs/teams/#teams),
this adds the basic organization teams CRUD. If this is all good and
gets accepted, I'll probably go on to add the rest of the team API, as
it's currently relevant to the project I'm working on :)
It also appears that the version in the README is quite a bit behind, so I updated that as well.
> Add the basic Teams API

- README.md
- lib/tentacat/issues/issues.ex
- test/fixture/vcr_cassettes/issues/issues#create.json
- test/fixture/vcr_cassettes/issues/issues#filter.json
- test/fixture/vcr_cassettes/issues/issues#find.json
- test/fixture/vcr_cassettes/issues/issues#list.json
- test/fixture/vcr_cassettes/issues/issues#update.json
- test/issues/issues_test.exs
Also build tests for existing issue methods
> Add support for issue create/update

- README.md
- lib/tentacat/organizations/hooks.ex
- test/fixture/vcr_cassettes/organizations/hooks#create.json
- test/fixture/vcr_cassettes/organizations/hooks#find.json
- test/fixture/vcr_cassettes/organizations/hooks#list.json
- test/fixture/vcr_cassettes/organizations/hooks#ping.json
- test/fixture/vcr_cassettes/organizations/hooks#remove.json
- test/fixture/vcr_cassettes/organizations/hooks#update.json
- test/organizations/hooks_test.exs
This seemed pretty straightforward.  Let me know if there are any questions with it.
> Add support for organization webhooks

- README.md
- lib/tentacat.ex
- lib/tentacat/pulls/review_requests.ex
- lib/tentacat/pulls/reviews.ex
- test/fixture/vcr_cassettes/pulls/review_requests#create.json
- test/fixture/vcr_cassettes/pulls/review_requests#list.json
- test/fixture/vcr_cassettes/pulls/review_requests#remove.json
- test/fixture/vcr_cassettes/pulls/reviews#list.json
- test/pulls/review_requests_test.exs
- test/pulls/reviews_test.exs
> Add Github Reviews endpoints

- lib/tentacat/repositories/forks.ex
Sorry about this, not sure how I missed it in my original PR :)
> Fix forks documentation to link to correct page

- lib/tentacat/teams/repositories.ex
- test/fixture/vcr_cassettes/teams/repositories#list.json
- test/teams/repositories_test.exs
- List all team repositories
Docs: https://developer.github.com/v3/orgs/teams/#list-team-repos
> Add endpoint for team repos

- lib/tentacat/repositories/collaborators.ex
- test/fixture/vcr_cassettes/repositories/collaborators#permission.json
- test/repositories/collaborators_test.exs
This PR wraps the following GitHub API call:
https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level
fixes https://github.com/edgurgel/tentacat/issues/177
> Add Tentacat.Repositories.Collaborators.permission function

- lib/tentacat.ex
- mix.exs
It's a quick fix for using httpoison >= 1.5. All tests passed.
> Fix function clauses error when Httpoison 1.5

- lib/tentacat/pulls/reviews.ex
- test/fixture/vcr_cassettes/pulls/reviews#create.json
- test/pulls/reviews_test.exs
Add support for the GitHub API that facilitates creating Reviews on a particular Pull Request. 
More info on the API here: https://developer.github.com/v3/pulls/reviews/#create-a-pull-request-review
Closes #174
> Add support for Create Reviews Endpoint

- lib/tentacat/gists.ex
- test/fixture/vcr_cassettes/gists#check_if_starred.json
- test/fixture/vcr_cassettes/gists#check_if_starred_not_starred.json
- test/fixture/vcr_cassettes/gists#create.json
- test/fixture/vcr_cassettes/gists#delete.json
- test/fixture/vcr_cassettes/gists#edit.json
- test/fixture/vcr_cassettes/gists#fork.json
- test/fixture/vcr_cassettes/gists#get_revision.json
- test/fixture/vcr_cassettes/gists#gist_get.json
- test/fixture/vcr_cassettes/gists#list_commits.json
- test/fixture/vcr_cassettes/gists#list_forks.json
- test/fixture/vcr_cassettes/gists#list_mine.json
- test/fixture/vcr_cassettes/gists#list_public.json
- test/fixture/vcr_cassettes/gists#list_public_with_params.json
- test/fixture/vcr_cassettes/gists#list_starred.json
- test/fixture/vcr_cassettes/gists#list_users.json
- test/fixture/vcr_cassettes/gists#star.json
- test/fixture/vcr_cassettes/gists#unstar.json
- test/gists_test.exs
In this PR, I will (slowly but surely) add [Gist endpoint](https://developer.github.com/v3/gists/). When done, it closes #128.
Progress:
Any feedback is highly appreciated 😺
> Gist endpoint

- lib/tentacat/starring.ex
- test/fixture/vcr_cassettes/starring#stargazers_failed.json
- test/fixture/vcr_cassettes/starring#stargazers_success.json
- test/starring_test.exs
> Add stargazers endpoint to Tentacat.User.Starring

- lib/tentacat/issues/issues.ex
Hi @edgurgel,
After using more `Tentacat.Issues` functions, I saw more documentation outdated so I went refreshing it a little bit.
Sorry that I had send them in two different PRs haha, I'll be more careful next time.
👋
> Update all documentation at Tentacat.Issues
