edgurgel/tentacat

- README.md
- lib/tentacat.ex
- lib/tentacat/contents.ex
- lib/tentacat/emails.ex
- lib/tentacat/feeds.ex
- lib/tentacat/followers.ex
- lib/tentacat/gitignore.ex
- lib/tentacat/hooks.ex
- lib/tentacat/keys.ex
- lib/tentacat/organizations.ex
- lib/tentacat/organizations/members.ex
- lib/tentacat/pulls.ex
- lib/tentacat/pulls/comments.ex
- lib/tentacat/pulls/commits.ex
- lib/tentacat/pulls/files.ex
- lib/tentacat/references.ex
- lib/tentacat/releases.ex
- lib/tentacat/releases/assets.ex
- lib/tentacat/repositories.ex
- lib/tentacat/repositories/branches.ex
- lib/tentacat/repositories/deployments.ex
- lib/tentacat/repositories/statuses.ex
- lib/tentacat/starring.ex
- lib/tentacat/trees.ex
- lib/tentacat/users.ex
- test/client_test.exs
This pull request make tentacat to support custom endpoint.
The main purpose is to access github enterprise API.
- Changes
- add new item `endpoint` to `Tentacat.Client` struct.
- implement `Tentacat.Client.new/1` and `Tentacat.Client.new/2`.
I'd appreciate any feedback. Thank you.
> support custom endpoint

- README.md
- lib/tentacat/issues.ex
- lib/tentacat/pulls.ex
By receiving a `filters` map and passing it through `URI.encode_query/1` it is
already prepared for future filters implemented on Github.
Also adds a new module to list and find issues.
> Add filters to pulls and Issues retrieving capability

- mix.exs
Hi All!
Newbie to the elixir world so sorry if this isn't right...
I recently added tentacat to my Phoenix project, running mix eps.get complained:
Looking up alternatives for conflicting requirements on httpoison
From mix.lock: 0.7.3
From tentacat v0.1.5: ~> 0.6.0
** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies
Updating the version of httpoison in tentacat fixed this. 
MIX_ENV=test mix do deps.get, test
Runs fine.
> Updated version of httpoison

- README.md
Current url leads to `https://github.com/edgurgel/tentacat/blob/master/hexdocs.pm/tentacat`
> fix url to doc on README

- fixture/vcr_cassettes/repositories#create.json
- fixture/vcr_cassettes/repositories#delete.json
- fixture/vcr_cassettes/repositories#list_mine.json
- fixture/vcr_cassettes/repositories#list_orgs.json
- fixture/vcr_cassettes/repositories#list_public.json
- fixture/vcr_cassettes/repositories#list_users.json
- fixture/vcr_cassettes/repositories#org_create.json
- fixture/vcr_cassettes/repositories#repo_get.json
- lib/tentacat.ex
- lib/tentacat/client.ex
- lib/tentacat/feeds.ex
- lib/tentacat/releases/assets.ex
- lib/tentacat/repositories.ex
- mix.exs
- test/client_test.exs
- test/repositories_test.exs
- test/tentacat_test.exs
* Adds ExVCR for recording http requests 
* Adds Tests for existing list repositories functionality
* Adds possibility to create, delete and get a repository
> Extend repositories functionality

- lib/tentacat.ex
- lib/tentacat/search.ex
The sort and order parameters are optional, so there is one function
that takes those arguments and one that doesn't.
> Adds the search code API

- README.md
Going through the examples in readme, I got a `httpoison`-related error message. Searching led me to a similar problem and a working solution on StackOverflow: http://stackoverflow.com/questions/31208923/hackney-fails-to-make-request-to-server
> Add `httpoison` requirement to readme

- lib/tentacat.ex
This allows overriding the default options in configuration, like so:
```elixir
config :tentacat, request_options: [
{:ssl, [
{:cacertfile, "/etc/mysvc/mycert.pem"}
]}
]
```
One possible solution to issue https://github.com/edgurgel/tentacat/issues/66.  :innocent:
> read and use additional :request_options on request!/5 

- lib/tentacat.ex
I was reading about the various pagination modes, but I couldn't figure
out a way to select a mode that was not :auto
I noted that there's a similar pattern for HTTPoison request options, so
I figured I'd take a stab at exposing the pagination mode in the same
way.
This works for my application, but I'm an Elixir super-n00b so I might just
be missing the way to get this option threaded through.
Either way, thanks for this project @edgurgel! 😀
> Expose pagination as an option

- README.md
- lib/tentacat/repositories/collaborators.ex
- test/fixture/vcr_cassettes/repositories/collaborators#add.json
- test/fixture/vcr_cassettes/repositories/collaborators#collaborator?.json
- test/fixture/vcr_cassettes/repositories/collaborators#delete.json
- test/fixture/vcr_cassettes/repositories/collaborators#list.json
- test/repositories/collaborators_test.exs
Adds API for [this](https://developer.github.com/v3/repos/collaborators/)
> Add repo collaborators API

- README.md
- lib/tentacat/releases.ex
- lib/tentacat/releases/assets.ex
The [`Dict`](http://elixir-lang.org/docs/stable/elixir/Dict.html) module is deprecated.
> Replace the use of the deprecated `Dict` module

- lib/tentacat/issues/comments.ex
- test/fixture/vcr_cassettes/issues/comments#update.json
- test/issues/comments_test.exs
According to [the API docs][1], the URI shouldn't include an issue
number, only a comment id:
PATCH /repos/:owner/:repo/issues/comments/:id
[1]: https://developer.github.com/v3/issues/comments/#edit-a-comment
> Fix Issues.Comments.update function

- lib/tentacat/releases.ex
- test/fixture/vcr_cassettes/releases#latest.json
- test/releases_test.exs
Why:
Prior to this changeset, in order to query for the latest release for a repository a developer was required to manually construct a get API request. It would be preferable to be able to make an API request in the same manner as other API endpoints.
This change addresses the issue by:
* Adding a `latest/3` method to fetch the most recent Release for a repository
> Add API for latest Release for repository

- lib/tentacat/repositories/tags.ex
Since Tentacat.get supports a lot of useful options like `pagination` and some resources already support passing options like https://github.com/edgurgel/tentacat/blob/v0.5.3/lib/tentacat/repositories.ex#L22
it seems like a good idea to add it to this function as well.
> Change Tentacat.Repositories.Tags.list to support options

- lib/tentacat/search.ex
- test/search_test.exs
https://github.com/edgurgel/tentacat/pull/70
Unexpected rate limit error occurs because of pagination and streaming in `search.ex`.
Now we can control pagination options in each functions.
```elixir
params = %{ q: repository_name, per_page: 1 }
options = [ pagination: :none ]
response = Tentacat.Search.repositories(params, client, options)
```
> Allow search mudule to take options

- lib/tentacat/issues/labels.ex
- test/fixture/vcr_cassettes/issues/labels#remove.json
- test/issues/labels_test.exs
This PR add the ```remove``` function in the ```Tentacat.Issues.Labels``` module.
see https://github.com/edgurgel/tentacat/issues/113
> add support for removing a label from an issue

- lib/tentacat/git/blobs.ex
- test/fixture/vcr_cassettes/git/blob#create.json
- test/fixture/vcr_cassettes/git/blob#get.json
- test/git/blobs_test.exs
- test/test_helper.exs
Adding [Git Blob](https://developer.github.com/v3/git/blobs/#custom-media-types) support.
Also adds a configuration to automatically strip the authentication tokens from cassettes when they're created.
> Add blob support for GitHub API

- lib/tentacat.ex
- mix.exs
The warnings were annoying me :P
```==> tentacat
Compiling 44 files (.ex)
warning: variable "extra_headers" does not exist and is being expanded to "extra_headers()", please use parentheses to remove the ambiguity or change the variable name
lib/tentacat.ex:87
warning: variable "extra_options" does not exist and is being expanded to "extra_options()", please use parentheses to remove the ambiguity or change the variable name
lib/tentacat.ex:87
warning: variable "extra_headers" does not exist and is being expanded to "extra_headers()", please use parentheses to remove the ambiguity or change the variable name
lib/tentacat.ex:122
warning: variable "extra_options" does not exist and is being expanded to "extra_options()", please use parentheses to remove the ambiguity or change the variable …
```
> Removed compile warnings

- lib/tentacat.ex
- test/fixture/vcr_cassettes/members#member_.json
- test/organizations/members_test.exs
Issue: #121 
Github can return redirect responses in some cases like when a repository is renamed, this PR will address that by handling 301, 302 and 307 responses which are documented [here](https://developer.github.com/v3/#http-redirects)
> Handling GitHub Redirects

- .travis.yml
Add more OTP and Elixir versions to travis matrix.
I don't know how far do you want to be backward compatible, but imo we can remove elixir 1.2.6
> Update travis matrix

- lib/tentacat.ex
- lib/tentacat/app.ex
- lib/tentacat/app/installations.ex
- test/app/installations_test.exs
- test/app_test.exs
- test/fixture/vcr_cassettes/app#me.json
- test/fixture/vcr_cassettes/app/installations#find.json
- test/fixture/vcr_cassettes/app/installations#list_mine.json
- test/fixture/vcr_cassettes/app/installations#token.json
- test/tentacat_test.exs
Added necessary components to use this library with the GitHub Apps and Installations API. There's enough here to authorize as an installation, do some basic installations querying, and get an auth token for a specific installation.
Includes:
* support for JWT authorization headers (and thus, clients)
* minimal coverage of `app` API
* minimal coverage of `installations` API
Happy to make changes based on feedback so let me know what you think!
> Add minimal support for GitHub Installations API

- lib/tentacat/milestones/milestones.ex
- test/fixture/vcr_cassettes/milesones/milestones#create.json
- test/fixture/vcr_cassettes/milesones/milestones#delete.json
- test/fixture/vcr_cassettes/milesones/milestones#find.json
- test/fixture/vcr_cassettes/milesones/milestones#list.json
- test/fixture/vcr_cassettes/milesones/milestones#update.json
- test/milestones/milestones_test.exs
I have taken the freedom to implement also the APIs for Milestones.
> Add support for Milestones

- lib/tentacat/app.ex
- lib/tentacat/app/installations.ex
- test/app/installations_test.exs
- test/app_test.exs
- test/fixture/vcr_cassettes/app#find.json
- test/fixture/vcr_cassettes/app/installations#list_repositories.json
Expands coverage of GitHub App and Installation API.
There are a two untested methods because they require an OAuth handshake by a user and an app (via the GitHub UI).
I was a little unsure of some naming in here so if anything sticks out and you have a suggestion, please let me know!
> more github installations api coverage

- lib/tentacat/comments/reactions.ex
- lib/tentacat/issues/comments/reactions.ex
- lib/tentacat/issues/reactions.ex
- lib/tentacat/pulls/comments/reactions.ex
- lib/tentacat/reactions.ex
- test/comments/reactions_test.exs
- test/fixture/vcr_cassettes/comments/reactions#create.json
- test/fixture/vcr_cassettes/comments/reactions#list.json
- test/fixture/vcr_cassettes/issues/comments/reactions#create.json
- test/fixture/vcr_cassettes/issues/comments/reactions#list.json
- test/fixture/vcr_cassettes/issues/reactions#create.json
- test/fixture/vcr_cassettes/issues/reactions#list.json
- test/fixture/vcr_cassettes/pulls/comments/reactions#create.json
- test/fixture/vcr_cassettes/pulls/comments/reactions#list.json
- test/fixture/vcr_cassettes/reactions#delete.json
- test/issues/comments/reactions_test.exs
- test/issues/reactions_test.ex
- test/pulls/comments/reactions_test.exs
- test/reactions_test.exs
This Pull Request supports the following actions on reactions
- List reactions for a commit comment
- Create reaction for a commit comment
- List reactions for an issue
- Create reaction for an issue
- List reactions for an issue comment
- Create reaction for an issue comment
- List reactions for a pull request review comment
- Create reaction for a pull request review comment
- Delete a reaction
More info: https://developer.github.com/v3/reactions/
> Add support for the Reactions APIs

- mix.exs
No breaking changes for exvcr between 0.8 and 0.9.
I didn't found any changelog on the exjsx repository, but this looks like a breaking change: https://github.com/talentdeficit/exjsx/commit/b52ec15af0d84f9ad204fd2309230cb1651269cd
> Upgrade exjsx and exvcr

- lib/tentacat/app.ex
- test/repositories_test.exs
```
warning: string() type use is discouraged. For character lists, use charlist()
type, for strings, String.t()
lib/tentacat/app.ex:28
warning: variable "list_public" does not exist and is being expanded to
"list_public()", please use parentheses to remove the ambiguity or change the
variable name
test/repositories_test.exs:67
```
> Fix a few compilation warnings

- lib/tentacat/client.ex
In #129, support was added for initializing a client with a JWT. However, the Dialyzer typedef wasn’t updated, which causes the following error:
```
The call 'Elixir.Tentacat.Client':new(#{'jwt':=<<_:16,_:_*8>> | [<<_:16,_:_*8>>]}) breaks the contract (auth()) -> t()
```
This commit fixes that issue.
> Update auth typedef to include JWT option

- lib/tentacat/organizations/members.ex
- test/fixture/vcr_cassettes/members#remove.json
This seems to do the same thing as the members api but it also removes invitations.
This seems like a fine change to me but if you'd prefer, I can change this to a new remove function (remove_memberships maybe?) if that sounds better.
> Switch to using the remove memberships api

- .gitignore
Right now, every time a test fails, `exvcr` generates the folder `fixture` with the errors, which shouldn't be included in the repo, so `fixture` is added to `.gitignore`
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
Make sure a test will fail
Run `mix test`
Git won't detect the generated files under `/fixture`
> Add /fixture to gitignore

- lib/tentacat.ex
- lib/tentacat/client.ex
- lib/tentacat/repositories.ex
- test/repositories_test.exs
- test/tentacat_test.exs
closes #144 
In some cases, (the default) `:auto` pagination would return the response body instead of the specified response tuple. I've refactored the `get/4` to keep align these cases and added a number of typings for clarity.
There are still some type issues in `tentacat.ex`, but I'd rather me (or someone else) tackle more of them in a future pull request.
Also fixed a small type mistake in `Client.t()`.
> fix auto pagination bug

- config/config.exs
- mix.exs
- test/test_helper.exs
* Updates HTTPoison to 1.3.0 (since 1.4.0+ requires [some work to be done on HTTPoison](https://github.com/edgurgel/tentacat/issues/152) itself)
* Updates ExVCR to 0.10.3 - required moving of VCR configuration to the Mix config file (solves the issue [encountered here](https://github.com/edgurgel/tentacat/pull/155#issuecomment-427704253))
> Update HTTPoison, ExVCR

- README.md
- lib/tentacat/users.ex
fix https://github.com/edgurgel/tentacat/issues/165
- update readme example for `Tentacat.Users.find`
The function has to be written in this order:
Tentacat.Users.find Tentacat.Client.new, "edgurgel"
> switch client and username parameter in readme example

- .gitignore
- guides/Getting Started.md
- mix.exs
This PR updates the documentation-generating dependencies to avoid issues with the latest versions of Elixir. It also introduces a new guide page, `Getting Started`, that condenses the setup steps into a single page on Hexdocs. The goal is to provide a focused guide for getting set up with this library.
If this is merged, the maintainers might wish to include a link to the getting started towards the top of the Readme file. Also note that the readme will now be the primary page on Hexdocs (as opposed to the API reference).
Please feel free to make changes and comment as appropriate. Thank you for your work on this project!
> Add Getting Started Guide

- lib/tentacat/repositories/deploy_keys.ex
- test/fixture/vcr_cassettes/repositories/deploy_keys#create.json
- test/fixture/vcr_cassettes/repositories/deploy_keys#find.json
- test/fixture/vcr_cassettes/repositories/deploy_keys#list.json
- test/fixture/vcr_cassettes/repositories/deploy_keys#remove.json
- test/repositories/deploy_keys_test.exs
I've recently had to interface with the Repositories Deploy Keys GitHub API on an Elixir project and so I noticed the support for that is missing in `tentacat`.
This PR implement all available Deploy Keys API [endpoints](https://developer.github.com/v3/repos/keys/). I've nested the module under `Repositories`, following in the current structure.
> Add support for Repositories Deploy Keys API 

- lib/tentacat/repositories/contents.ex
- test/fixture/vcr_cassettes/repositories/contents#content.json
- test/repositories/contents_test.exs
> Gets the contents of a file or directory in a repository
Doc: https://developer.github.com/v3/repos/contents/#get-contents
Do you want to be able to manage options like `ref` or when it's a directory (we get a listing).
For the last one, checking the other endpoints, it seems the philosophy is to be only an API wraper.
What about the the `ref` option then ?
> Add support for Repositories Contents API

- lib/tentacat/repositories/contributors.ex
Hey guys,
Thanks for the lib. I've just noticed there is a typo in the doc, this PR fixes it.
Cheers!
> Fix a typo in Tentacat.Repositories.Contributors docs

- lib/tentacat/issues/comments/reactions.ex
- lib/tentacat/issues/reactions.ex
- test/fixture/vcr_cassettes/issues/comments/reactions#delete.json
- test/fixture/vcr_cassettes/issues/reactions#delete.json
- test/issues/comments/reactions_test.exs
- test/issues/reactions_test.exs
This PR adds support for two Reactions Delete endpoints:
1. Delete a reaction on an issue: https://developer.github.com/v3/reactions/#delete-an-issue-reaction
2. Delete a reaction on an issue comment: https://developer.github.com/v3/reactions/#delete-an-issue-comment-reaction
PartiallyCloses #187
I'll add other
> Delete reactions endpoint for Issues and its comments

- lib/tentacat/issues/issues.ex
Just a little typo fixed at _list issues_ documentation.
**Error:**
>** (Protocol.UndefinedError) protocol String.Chars not implemented for %Tentacat.Client{auth: %{access_token: "xxxxx"}, endpoint: "https://api.github.com/"} of type Tentacat.Client (a struct).
>
>This protocol is implemented for the following type(s): Float, DateTime, Time, List, Version.Requirement, Atom, Integer, Version, Date, BitString, NaiveDateTime, URI
> Fix little documentation typo at Tentacat.Issues

- config/config.exs
This PR fixes the issue when running the `MIX_ENV=test mix vcr` where missing `custom_cassette_library_dir` will default to `nil`.
```
...
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1    
The following arguments were given to IO.chardata_to_string/1:
nil
Attempted function clauses (showing 2 out of 2):
def chardata_to_string(string) when is_binary(string)
def chardata_to_string(list) when is_list(list)
(elixir 1.10.3) lib/io.ex:572: IO.chardata_to_string/1
(elixir 1.10.3) lib/file.ex:214: File.exists?/2
lib/exvcr/task/runner.ex:17: anonymous fn/1 in ExVCR.Task.Runner.show_vcr_cassettes/1
(elixir 1.10.3) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
(elixir 1.10.3) lib/enum.ex:783: Enum.each/2
(mix 1.10.3) lib/mix/task.ex:330: Mix.Task.run_task/3 …
```
> Fix missing exvcr custome path causing error

- lib/tentacat/issues/labels.ex
Github expects the labels to be encoded so the current implementation doesn't account for labels with spaces or other special characters.
> Encode label when deleting

- mix.exs
Using `httpoison v1` conflicts with libraries like [openai](https://github.com/mgallo/openai.ex) which uses `httpoison v2`
> Updating libs
